

title: Resume
url: 'https://fly2rain.github.io/'
baseurl: '' #change it according to your repository name

name: Feiyun Zhu

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
tagline: Health.Truth.Freedom.Love
pic: profile_fyzhu.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: fyzhu0915@gmail.com
website: https://fly2rain.github.io/ #do not add http://
# website: https://scholar.google.com/citations?user=QoYehcTZ5ewC&hl=en
linkedin: https://www.linkedin.com/feed/
github: fly2rain
# twitter: '@xinliangzhu08'

#Update all the sections by editing the files inside _includes folder.
